# Generated by Django 4.0.4 on 2022-06-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_pic',
            field=models.ImageField(default='cover-pic.jpg', upload_to=''),
        ),
    ]
