# Generated by Django 4.0.4 on 2022-06-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_cover_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_pic',
            field=models.ImageField(default='default-cover-pic.jpg', upload_to=''),
        ),
    ]
